
on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: "docker login"
        run: docker login --username ${{secrets.USERNAME_TOKEN}} --password ${{secrets.DOCKER_TOKEN}}
      - name: "build image"
        run: docker build -t ${{secrets.USERNAME_TOKEN}}/myimagesection2
      - name: "pushing image"
        run: docker push ${{secrets.USERNAME_TOKEN}}/myimagesection2

      